- name: Catalogue setup
  hosts: rabbitmq
  become: yes
  tasks:
    - name: setup rabbitmq repo file
      ansible.builtin.shell: curl -sL https://rpm.nodesource.com/setup_lts.x | bash
    - name: Install nodejs
      ansible.builtin.yum:
        name: nodejs
        state: present
    - name: check user exit or not
      ansible.builtin.command: id roboshop
      register: output
    - name: Create a user
      ansible.builtin.user:
        name: roboshop
      when: output.rc!=0
    - name: Download catalogue.zip
      ansible.builtin.get_url:
        url: https://roboshop-builds.s3.amazonaws.com/catalogue.zip
        dest: /tmp/catalogue.zip
    - name: unzip catalogue.zip file
      ansible.builtin.unarchive:
        src: /tmp/catalogue.zip
        dest: /app/
    - name: install dependencies
      ansible.builtin.shell: npm install
      args:
        chdir: /app/
    - name: copy catalogue service file
      ansible.builtin.copy:
        src: catalogue.service
        dest: /etc/systemd/system/

    - name: enable and start catalogue service
      ansible.builtin.systemd_service:
        state: started
        daemon_reload: true
        enabled: yes
        name: catalogue
    - name: copy mongodb repo file
      ansible.builtin.copy:
        src: mongo.repo
        dest: /etc/yum.repos.d/
    - name: Install mongodb client
      ansible.builtin.yum:
        name: mongodb-org-shell
        state: present

    - name: Load schema
      ansible.builtin.shell: mongo --host mongodb.nareshdevops.online < /app/schema/catalogue.js
    
