- name: dispatch setup
  hosts: dispatch
  become: yes
  tasks:
    - name: Install python
      ansible.builtin.yum:
        name: golang
        state: present
    - name: check roboshop user exit or not
      ansible.builtin.command: id roboshop
      register: output
      ignore_errors: True
    - name: Create a roboshop user 
      ansible.builtin.user:
        name: roboshop
      when: output.rc!=0
    - name: Create a directory if it does not exist
      ansible.builtin.file:
        path: /app/
        state: directory
    - name: Download dispatch.zip
      ansible.builtin.get_url:
        url: https://roboshop-builds.s3.amazonaws.com/dispatch.zip
        dest: /tmp/dispatch.zip
    - name: unzip dispatch.zip file
      ansible.builtin.unarchive:
        src: /tmp/dispatch.zip
        dest: /app/
        remote_src: yes
    - name: install dependencies
      ansible.builtin.command: "{{item}}"
      args:
        chdir: /app/
      loop:
        - go mod init dispatch
        - go get 
        - go build
    - name: copy dispatch service file
      ansible.builtin.copy:
        src: dispatch.service
        dest: /etc/systemd/system/
    - name: enable and start dispatch service
      ansible.builtin.systemd_service:
        state: started
        daemon_reload: true
        enabled: yes
        name: dispatch

    
    
