- name: payment setup
  hosts: payment
  become: yes
  tasks:
    - name: Install python
      ansible.builtin.yum:
        name: "{{item}}"
        state: present
      loop:
        - python36
        - gcc
        - python3-devel
    - name: check roboshop user exit or not
      ansible.builtin.command: id roboshop
      register: output
      ignore_errors: True
    - name: Create a roboshop user 
      ansible.builtin.payment:
        name: roboshop
      when: output.rc!=0
    - name: Create a directory if it does not exist
      ansible.builtin.file:
        path: /app/
        state: directory
    - name: Download payment.zip
      ansible.builtin.get_url:
        url: https://roboshop-builds.s3.amazonaws.com/payment.zip
        dest: /tmp/payment.zip
    - name: unzip payment.zip file
      ansible.builtin.unarchive:
        src: /tmp/payment.zip
        dest: /app/
        remote_src: yes
    - name: install dependencies
      ansible.builtin.command: pip3.6 install -r requirements.txt
      args:
        chdir: /app/
    - name: copy payment service file
      ansible.builtin.copy:
        src: payment.service
        dest: /etc/systemd/system/
    - name: enable and start payment service
      ansible.builtin.systemd_service:
        state: started
        daemon_reload: true
        enabled: yes
        name: payment

    
    
