- name: rabbitmq setup
  hosts: rabbitmq
  become: yes
  tasks:
    - name: setup rabbitmq repo file
      ansible.builtin.shell: "{{item}}"
      loop:
        - "curl -s https://packagecloud.io/install/repositories/rabbitmq/erlang/script.rpm.sh | bash"
        - "curl -s https://packagecloud.io/install/repositories/rabbitmq/rabbitmq-server/script.rpm.sh | bash"
    - name: Install rabbitmq
      ansible.builtin.yum:
        name: rabbitmq-server
        state: present
    - name: start and enable rabbitmq service
      ansible.builtin.service:
        name: rabbitmq-server
        state: started
        enabled: yes
    - name: add roboshop user and password
      ansible.builtin.command: rabbitmqctl add_user roboshop roboshop123

    - name: Set permissions for roboshop user
      ansible.builtin.command: rabbitmqctl set_permissions -p / roboshop ".*" ".*" ".*"

