- name: Redis setup
  hosts: redis
  become: yes
  tasks:
    - name: redis repo file install
      ansible.builtin.command:
        yum install https://rpms.remirepo.net/enterprise/remi-release-8.rpm -y
    - name:
      ansible.builtin.yum:
        name: redis>=6.2
        state: present
    - name: Update listen address from 127.0.0.1 to 0.0.0.0 in /etc/redis.conf
      ansible.builtin.replace:
        path: /etc/redis.conf
        regexp: '127.0.0.1'
        replace: '0.0.0.0'
    - name: start and enable redis service
      ansible.builtin.service:
        name: redis
        state: started
        enabled: yes
